/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.cg.gui;

import java.util.ArrayList;
import java.util.List;

import javax.swing.table.TableCellEditor;
import javax.swing.table.TableModel;

import com.github.cg.component.StringUtils;
import com.github.cg.gui.tablemodel.AttributeTableModel;
import com.github.cg.gui.util.JFrameUtils;
import com.github.cg.model.Attribute;
import com.github.cg.model.AttributeManyToOne;
import com.github.cg.model.AttributeOneToMany;

/**
 *
 * @author pablo.filetti@gmail.com
 */
public class PnAttributes extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;
	
	private final AttributeTableModel tmAttributes;

	private List<String> patterns;
	private List<String> formTypes;

    /**
     * Creates new form FrmAttributes
     */
	public PnAttributes() {
		this(new ArrayList<String>(), new ArrayList<String>());
	}

    public PnAttributes(List<String> patterns, List<String> formTypes) {
		
    	this.patterns = patterns;
		this.formTypes = formTypes;
		        
		initComponents();
        
        tmAttributes = new AttributeTableModel(tblAttributes, this.patterns, this.formTypes);    	
    }
    
    public void initialize(List<Attribute> attributes) {
                	
    	if (attributes != null) {
        	getTmAttributes().setAttributes(attributes);
        }
        // Para testes
        else {
            attributes = new ArrayList<Attribute>();

            attributes.add(new Attribute());
            attributes.add(new AttributeOneToMany());
            attributes.add(new AttributeManyToOne());

            getTmAttributes().setAttributes(attributes);
            //getTmAttributes().hideColumnRenderColumn();
            //getTmAttributes().hideColumnRenderFilter();
            //getTmAttributes().hideColumnRenderForm();
            //getTmAttributes().hideColumnAttributeDescription();    
            getTmAttributes().fireTableDataChanged();
        }
    }

    public AttributeTableModel getTmAttributes() {
        return tmAttributes;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnAttributes = new javax.swing.JScrollPane();
        tblAttributes = new javax.swing.JTable() {

            public TableCellEditor getCellEditor(int row, int column) {

                TableModel tm = getModel();

                TableCellEditor cellEditor = null;

                if (tm instanceof AttributeTableModel) {
                    AttributeTableModel atm = (AttributeTableModel) tm;
                    cellEditor = atm.getCellEditor(row, column);
                }

                if (cellEditor != null) {
                    return cellEditor;
                }   
                else {
                    return super.getCellEditor(row, column);
                }
            }
        };

        setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos"));
        setPreferredSize(new java.awt.Dimension(720, 113));

        pnAttributes.setAutoscrolls(true);

        tblAttributes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        pnAttributes.setViewportView(tblAttributes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnAttributes, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnAttributes, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane pnAttributes;
    private javax.swing.JTable tblAttributes;
    // End of variables declaration//GEN-END:variables

	public boolean validateAttributes() {
		
		for (Attribute attr : getTmAttributes().getEntities()) {
			
			if (attr instanceof AttributeManyToOne) {
				
				AttributeManyToOne attribute = (AttributeManyToOne) attr;
				
				if (StringUtils.getInstance().isNullOrEmpty(attribute.getDescriptionAttributeOfAssociation())) {
					JFrameUtils.showErro("Erro de validação", "O Atributo descrição da associação " + attribute.getName() + " não foi informado!");
					return false;
				}
			}
			else if (attr instanceof AttributeOneToMany && this.formTypes.size() > 0) {
				
				AttributeOneToMany attribute = (AttributeOneToMany) attr;
				
				if (StringUtils.getInstance().isNullOrEmpty(attribute.getFormType())) {
					JFrameUtils.showErro("Erro de validação", "O Atributo tipo de formulário da associação " + attribute.getName() + " não foi informado!");
					return false;
				}
			}
		}
		
		return true;
	}

	public void save() {		
		for (Attribute attribute : getTmAttributes().getEntities()) {
			if (StringUtils.getInstance().isNullOrEmpty(attribute.getLabel())) {
				attribute.setLabelDefault();
			}
		}	
	}
}
