/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atos.gc.gui;

/**
 *
 * @author 205327
 */
public class FrmAttribute extends javax.swing.JPanel {

    /**
     * Creates new form FrmAttribute
     */
    public FrmAttribute() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFieldName = new javax.swing.JLabel();
        txtLabel = new javax.swing.JTextField();
        ckbRenderGridColumn = new javax.swing.JCheckBox();
        ckbRenderGridFilter = new javax.swing.JCheckBox();
        ckbRenderWinFrm = new javax.swing.JCheckBox();
        pnAttributeType = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblFieldName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFieldName.setText("Attribute Name:");

        txtLabel.setText("jTextField1");

        ckbRenderGridColumn.setToolTipText("Renderizar Grid Column");
        ckbRenderGridColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbRenderGridColumnActionPerformed(evt);
            }
        });

        ckbRenderGridFilter.setToolTipText("Renderizar Grid Filter");
        ckbRenderGridFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbRenderGridFilterActionPerformed(evt);
            }
        });

        ckbRenderWinFrm.setToolTipText("Renderizar WinFrm");

        javax.swing.GroupLayout pnAttributeTypeLayout = new javax.swing.GroupLayout(pnAttributeType);
        pnAttributeType.setLayout(pnAttributeTypeLayout);
        pnAttributeTypeLayout.setHorizontalGroup(
            pnAttributeTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );
        pnAttributeTypeLayout.setVerticalGroup(
            pnAttributeTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbRenderGridColumn)
                .addGap(2, 2, 2)
                .addComponent(ckbRenderGridFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbRenderWinFrm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnAttributeType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ckbRenderWinFrm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ckbRenderGridColumn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFieldName)
                            .addComponent(txtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ckbRenderGridFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnAttributeType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ckbRenderGridColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbRenderGridColumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbRenderGridColumnActionPerformed

    private void ckbRenderGridFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbRenderGridFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbRenderGridFilterActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckbRenderGridColumn;
    private javax.swing.JCheckBox ckbRenderGridFilter;
    private javax.swing.JCheckBox ckbRenderWinFrm;
    private javax.swing.JLabel lblFieldName;
    private javax.swing.JPanel pnAttributeType;
    private javax.swing.JTextField txtLabel;
    // End of variables declaration//GEN-END:variables
}
