/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atos.gc.gui;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

import br.com.atos.gc.model.Attribute;
import br.com.atos.gc.model.AttributeId;
import br.com.atos.gc.model.AttributeManyToOne;
import br.com.atos.gc.model.AttributeOneToMany;
import br.com.atos.gc.model.Entity;
import br.com.atos.gc.model.Gender;
import br.com.atos.gc.model.Target;
import br.com.atos.gc.model.TargetConfig;
import br.com.atos.gc.util.EntityComboBoxModel;
import br.com.atos.utils.StringUtils;
import br.com.atos.utils.swing.JFrameUtils;

/**
 *
 * @author 205327
 */
public class WinFrmEntity extends javax.swing.JDialog {
    
	private static final long serialVersionUID = 1L;
	
	private EntityComboBoxModel<Gender> cmGender;
    private Entity entity;
    private int status;
    
    /**
     * Creates new form WinFrmEntity
     */
    public WinFrmEntity(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        
        initComponents();
        
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);			    
        
        txtLabel.requestFocus();
        
        cmGender = new EntityComboBoxModel<Gender>(Gender.values()) {
            @Override
            public String getLabel(Gender item) {
                return item.getDescription();
            }
        };
        
        cbbGender.setModel(cmGender);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbbGender = new javax.swing.JComboBox();
        txtLabel = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        frmAttributes = new br.com.atos.gc.gui.FrmAttributes();
        txtTarget = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Entidade");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setPreferredSize(new java.awt.Dimension(1024, 800));

        jLabel1.setText("Rótulo:");

        jLabel2.setText("Gênero: ");

        cbbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtTarget.setEditable(false);

        jLabel3.setText("Target:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frmAttributes, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOk))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbGender, 0, 300, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTarget, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(txtLabel))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(frmAttributes, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
    	save();        
    }//GEN-LAST:event_btnOkActionPerformed

    private void save() {
    	
    	// Verifica se foi informado os dados
        if (cmGender.getSelectedEntity() == null) {
            JFrameUtils.showErro("Erro de validação", "O Gênero não foi informado!");
            return;
        }
        
        if (!getFrmAttributes().validateAttributes()) {
        	return;
        }
        
        if (StringUtils.isNullOrEmpty(txtLabel.getText())) {
			getEntity().setLabelDefault();	
		}
		else {
			getEntity().setLabel(txtLabel.getText());
		}
		
		getEntity().setGender(cmGender.getSelectedEntity());
		
		getFrmAttributes().save();
		
		status = JOptionPane.OK_OPTION;
		
		setVisible(false);
	}

	private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        status = JOptionPane.CANCEL_OPTION;
		setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinFrmEntity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinFrmEntity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinFrmEntity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinFrmEntity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WinFrmEntity dialog = new WinFrmEntity(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.start(null, null);
            }
        });
    }

	public Entity getEntity() {
		return entity;
	}
	
    public void start(Entity entity, Target target) {
    	
    	TargetConfig colRender = target.getWinFrmEntity();
    	
        this.entity = entity;
		        
        if (entity != null) {

        	setTitle(getTitle() + " - " + entity.getClazz().getName());
        	
            txtLabel.setText(getEntity().getLabel());
            cmGender.setSelectedEntity(getEntity().getGender());
            
            List<Attribute> attributes = new ArrayList<Attribute>();
            
            for (Attribute attribute : getEntity().getAttributes()) {
            	
            	boolean add = false;
            	
            	if (attribute instanceof AttributeId) {
            		add = true;
            	}
            	else if (attribute instanceof AttributeManyToOne) {
            		add = true;
            	}
            	else if (attribute instanceof AttributeOneToMany) {
            		if (colRender.isShowAttributesOneToMany()) {
            			add = true;
            		}
            	}
            	else {
            		add = true;
            	}

            	if (add) {
            		attributes.add(attribute);
            	}
            }
            
            getFrmAttributes().initialize(attributes);
        }
        // Para testes
        else {
            getFrmAttributes().initialize(null);
        }
		
		
		
		if (colRender != null) {			
			if (!colRender.isRenderRenderColumn()) {
				getFrmAttributes().getTmAttributes().hideColumnRenderColumn();
			}
			if (!colRender.isRenderRenderFilter()) {
				getFrmAttributes().getTmAttributes().hideColumnRenderFilter();
			}
			if (!colRender.isRenderRenderForm()) {
				getFrmAttributes().getTmAttributes().hideColumnRenderForm();
			}			
			if (!colRender.isRenderAttributeDescription()) {
				getFrmAttributes().getTmAttributes().hideColumnAttributeDescription();
			}
			if (!colRender.isRenderFormType()) {
				getFrmAttributes().getTmAttributes().hideColumnFormType();
			}
		}
		
		JFrameUtils.setCenterLocation(this);
        status = JOptionPane.CANCEL_OPTION;
        setVisible(true);
    }    

    public FrmAttributes getFrmAttributes() {
        return (FrmAttributes) frmAttributes;
    }
    
    public boolean isStatusOK() {
    	return status == JOptionPane.OK_OPTION;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox cbbGender;
    private br.com.atos.gc.gui.FrmAttributes frmAttributes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtLabel;
    private javax.swing.JTextField txtTarget;
    // End of variables declaration//GEN-END:variables
}
